name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Eliminar Stack de CloudFormation
        run: |
          aws cloudformation delete-stack --stack-name StackExamenSarahJulio
          echo "Esperando a que el Stack sea eliminado por completo..."
          aws cloudformation wait stack-delete-complete --stack-name StackExamenSarahJulio